version: "3.7"

services:
  dockerbot:
    image: techblog/dockerbot
    container_name: dockerbot
    network_mode: host
    cap_add:
       - NET_ADMIN
    privileged: true
    restart: always
    environment:
      - API_KEY=
      - ALLOWED_IDS=
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
 
