version: "3.7"

services:
  ttsbot:
    image: techblog/ttsbot
    #build: https://github.com/t0mer/ttsbot.git
    container_name: ttsbot
    restart: always
    labels:
      - "com.ouroboros.enable=true"
    environment:
      - BOT_API_KEY=
      - TTS_LANG=he-IL-Asaf-Hebrew
      - TTS_PITCH=100
      - TTS_BITRATE=128k
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
